import { useState, useEffect, useRef, useCallback } from 'react';
import { TemplatePanel, ApplicationEditorView } from './PatentTemplate';
import { store } from './lib/store';
import { extractFileText } from './lib/extractText';

// ══════════════════════════════════════════════════════════════════════════════
//  PATENTGUARD v4 — Global Ledger · ZK Proofs · IPFS · AI Chatbot · Laws
// ══════════════════════════════════════════════════════════════════════════════

const API_BASE = import.meta.env.VITE_API_BASE || "https://green-guests-mix.loca.lt";
const FETCH_HEADERS = { "bypass-tunnel-reminder": "true", "Content-Type": "application/json" };
const FORM_HEADERS  = { "bypass-tunnel-reminder": "true" };

// ══════════════════════════════════════════════════════════════════════════════
//  DUAL KEY + ZK PROOF CRYPTOGRAPHIC ENGINE
//
//  USER KEY (PG-USER-YYYY-XXXXXXXX-CHK)  ← generated by applicant from document
//  GOV  KEY (USPTO-YYYY-XXXXXXXX-CHK)    ← generated by examiner FROM user key
//  LEDGER HASH = sha256(docHash + userKey + govKey + timestamp)
//  Neither key alone creates a valid ledger entry.
// ══════════════════════════════════════════════════════════════════════════════

async function sha256(text) {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(text));
  return Array.from(new Uint8Array(buf)).map(b => b.toString(16).padStart(2,"0")).join("");
}
async function generateIPFSCid(content) {
  const hash = await sha256(content + Date.now());
  return `Qm${hash.slice(0,44)}`;
}

// ── ZK Commitment (simplified Pedersen scheme) ────────────────────────────────
// commitment = H(content + salt)              → hides content, verifiable
// nullifier  = H(salt + "null:" + H(content)) → prevents double-submission
// bindingKey = H(commitment + nullifier)       → links all components
async function zkCommit(content, salt) {
  const contentHash = await sha256(content);
  const commitment  = await sha256(content + salt);
  const nullifier   = await sha256(salt + "null:" + contentHash);
  const bindingKey  = await sha256(commitment + nullifier);
  return { commitment, nullifier, bindingKey, contentHash, salt, timestamp: Date.now(), proofType: "SHA256-Pedersen-v1" };
}
async function zkVerify(content, salt, commitment, nullifier, contentHash) {
  const rHash   = await sha256(content);
  const rCommit = await sha256(content + salt);
  const rNull   = await sha256(salt + "null:" + rHash);
  const hOk = rHash   === contentHash;
  const cOk = rCommit === commitment;
  const nOk = rNull   === nullifier;
  return {
    allValid: hOk && cOk && nOk, commitmentValid: cOk, nullifierValid: nOk, hashValid: hOk,
    reason: hOk && cOk && nOk ? "ZK proof verified ✓" :
      [!hOk && "Content hash mismatch", !cOk && "Commitment mismatch", !nOk && "Nullifier mismatch"].filter(Boolean).join(" · ")
  };
}

// ── User Key (applicant generates from document) ─────────────────────────────
// Format: PG-USER-YYYY-XXXXXXXX-CHK
async function generateUserKey(content, timestamp) {
  const contentHash = await sha256(content);
  const year   = new Date(timestamp).getFullYear();
  const serial = (await sha256(contentHash + timestamp)).slice(0,8).toUpperCase();
  const base   = `PG-USER-${year}-${serial}`;
  const chk    = (await sha256(base)).slice(0,4).toUpperCase();
  return `${base}-${chk}`;
}
async function validateUserKey(key) {
  const re = /^PG-USER-(\d{4})-([A-Z0-9]{8})-([A-Z0-9]{4})$/;
  const match = key.match(re);
  if (!match) return { valid: false, reason: "Format must be PG-USER-YYYY-XXXXXXXX-XXXX" };
  const [, year, serial, chk] = match;
  const expectedChk = (await sha256(`PG-USER-${year}-${serial}`)).slice(0,4).toUpperCase();
  if (chk !== expectedChk) return { valid: false, reason: `Checksum mismatch — expected ${expectedChk}` };
  return { valid: true, year: parseInt(year), serial };
}

// ── Government Key (examiner generates FROM user key — cryptographically bound) ─
// Format: USPTO-YYYY-XXXXXXXX-CHK
// Serial = sha256(userKey + "gov-bind-v1").slice(0,8) — binds to specific user key
async function generateGovKey(userKey) {
  const year   = new Date().getFullYear();
  const serial = (await sha256(userKey + "gov-bind-v1")).slice(0,8).toUpperCase();
  const base   = `USPTO-${year}-${serial}`;
  const chk    = (await sha256(base)).slice(0,4).toUpperCase();
  return `${base}-${chk}`;
}
async function validateGovKey(key) {
  const re = /^USPTO-(\d{4})-([A-Z0-9]{8})-([A-Z0-9]{4})$/;
  const match = key.match(re);
  if (!match) return { valid: false, reason: "Format must be USPTO-YYYY-XXXXXXXX-XXXX" };
  const [, year, serial, chk] = match;
  const yr = parseInt(year);
  if (yr < 1990 || yr > new Date().getFullYear() + 1) return { valid: false, reason: `Year ${year} out of range` };
  const expectedChk = (await sha256(`USPTO-${year}-${serial}`)).slice(0,4).toUpperCase();
  if (chk !== expectedChk) return { valid: false, reason: `Checksum mismatch — expected ${expectedChk}` };
  return { valid: true, year: yr, serial };
}

// ── Key Pair Binding Verification ─────────────────────────────────────────────
// Proves the gov key was cryptographically derived from THIS user key
async function verifyKeyPair(userKey, govKey) {
  const uCheck = await validateUserKey(userKey);
  if (!uCheck.valid) return { valid: false, reason: `User key invalid: ${uCheck.reason}`, userKeyValid: false, govKeyValid: false, bound: false };
  const gCheck = await validateGovKey(govKey);
  if (!gCheck.valid) return { valid: false, reason: `Gov key invalid: ${gCheck.reason}`, userKeyValid: true, govKeyValid: false, bound: false };
  const govSerial      = govKey.match(/^USPTO-\d{4}-([A-Z0-9]{8})/)[1];
  const expectedSerial = (await sha256(userKey + "gov-bind-v1")).slice(0,8).toUpperCase();
  if (govSerial !== expectedSerial) return { valid: false, reason: "Keys are NOT paired — gov key was not issued for this user key", userKeyValid: true, govKeyValid: true, bound: false };
  return { valid: true, reason: "Key pair verified — cryptographic binding confirmed ✓", userKeyValid: true, govKeyValid: true, bound: true };
}

// ── Combined Ledger Hash (requires both keys) ─────────────────────────────────
async function createLedgerHash(contentHash, userKey, govKey, timestamp) {
  return sha256(`${contentHash}:${userKey}:${govKey}:${timestamp}`);
}

// ── Full ledger entry verification ────────────────────────────────────────────
async function verifyLedgerEntry(entry) {
  const keyPair = (entry.userKey && entry.govKey)
    ? await verifyKeyPair(entry.userKey, entry.govKey)
    : { valid: false, reason: "Missing user key or gov key" };
  const recomputedHash = (entry.contentHash && entry.userKey && entry.govKey && entry.timestamp)
    ? await createLedgerHash(entry.contentHash, entry.userKey, entry.govKey, entry.timestamp)
    : null;
  const ledgerHashCheck = recomputedHash
    ? { valid: recomputedHash === entry.ledgerHash, reason: recomputedHash === entry.ledgerHash ? "Ledger hash verified ✓" : "Ledger hash mismatch — possible tampering" }
    : { valid: false, reason: "Missing fields for hash verification" };
  const allValid = keyPair.valid && ledgerHashCheck.valid;
  return { verified: allValid, reason: allValid ? "All checks passed ✓" : [!keyPair.valid && keyPair.reason, !ledgerHashCheck.valid && ledgerHashCheck.reason].filter(Boolean).join(" · "), keyPair, ledgerHashCheck };
}

async function generateDemoUserKey(sampleContent) {
  return generateUserKey(sampleContent || "demo patent content " + Date.now(), Date.now());
}

// ── Jurisdictional law database ───────────────────────────────────────────────
const JURISDICTIONS = {
  US: {
    name:"United States (USPTO)", code:"US", flag:"🇺🇸",
    authority:"USPTO — United States Patent & Trademark Office",
    timeline:"18mo to publication · 2-3yr to grant",
    fees:{ micro:"$320", small:"$800", large:"$1,600", note:"Basic filing fee 2024" },
    laws:[
      { section:"35 USC § 101", title:"Patent-Eligible Subject Matter", summary:"Inventions must be a process, machine, manufacture, or composition of matter. Abstract ideas, natural phenomena, and laws of nature are excluded.", keywords:["software","algorithm","method","process","machine"] },
      { section:"35 USC § 102", title:"Novelty", summary:"Cannot be patented if already patented, described in a publication, in public use, on sale, or otherwise available to the public before the effective filing date.", keywords:["novelty","prior art","public use","on sale","publication"] },
      { section:"35 USC § 103", title:"Non-Obviousness", summary:"Not patentable if differences between the claimed invention and prior art would be obvious to a person having ordinary skill in the relevant field.", keywords:["obvious","prior art","PHOSITA","combination","motivation"] },
      { section:"35 USC § 112", title:"Written Description & Enablement", summary:"Specification must contain a written description and teach how to make and use the invention in full, clear, concise, and exact terms. Claims must be definite.", keywords:["description","enablement","claims","specification","indefinite"] },
      { section:"35 USC § 119", title:"Priority Claim", summary:"Claim priority from earlier filing within 12 months (utilities) or 6 months (designs) of the priority date under Paris Convention.", keywords:["priority","foreign","provisional","Paris Convention"] },
    ],
    filingRequirements:[
      "Specification (background, summary, detailed description)",
      "At least one independent claim",
      "Abstract (max 150 words)",
      "Drawings (if necessary to understand invention)",
      "Oath or declaration by inventor(s)",
      "Application Data Sheet (ADS)",
      "Filing fees (micro/small/large entity rates)",
    ],
  },
  EU: {
    name:"European Patent Office (EPO)", code:"EU", flag:"🇪🇺",
    authority:"EPO — European Patent Organisation",
    timeline:"18mo to publication · 3-4yr to grant",
    fees:{ basic:"€135 online", search:"€1,460", note:"EPO fee schedule 2024" },
    laws:[
      { section:"EPC Art. 52", title:"Patentable Inventions", summary:"Patents granted for inventions in all fields of technology that are new, involve an inventive step, and are susceptible of industrial application. Excludes discoveries, mental acts, presentations of information.", keywords:["technology","industrial","discovery","mental","software"] },
      { section:"EPC Art. 54", title:"Novelty", summary:"An invention is new if it does not form part of the state of the art — everything made available to the public before the filing date.", keywords:["novelty","state of art","public","disclosure","anticipation"] },
      { section:"EPC Art. 56", title:"Inventive Step", summary:"An invention involves an inventive step if it is not obvious to a person skilled in the art having regard to the state of the art.", keywords:["inventive step","obvious","skilled","problem-solution"] },
      { section:"EPC Art. 83", title:"Sufficiency of Disclosure", summary:"Application must disclose the invention sufficiently clearly and completely for it to be carried out by a person skilled in the art.", keywords:["disclosure","sufficiency","clear","complete","enable"] },
      { section:"EPC Art. 84", title:"Claims", summary:"Claims shall define the matter for which protection is sought. They shall be clear, concise, and supported by the description.", keywords:["claims","clear","concise","supported","protection"] },
    ],
    filingRequirements:[
      "Request for grant (Form 1001)",
      "Description of the invention",
      "Claims (independent + dependent)",
      "Abstract",
      "Drawings if referred to",
      "Filing fee + search fee",
      "Designation of contracting states",
    ],
  },
  PCT: {
    name:"PCT International (WIPO)", code:"PCT", flag:"🌐",
    authority:"WIPO — World Intellectual Property Organization",
    timeline:"30mo to national phase · varies by country",
    fees:{ basic:"$1,330 USD", note:"International filing + ISA/US fee 2024" },
    laws:[
      { section:"PCT Art. 11", title:"Filing Date", summary:"International filing date accorded when applicant is national/resident of a Contracting State, application in prescribed language, and contains required elements.", keywords:["filing date","international","contracting state","language"] },
      { section:"PCT Art. 17", title:"International Search", summary:"The ISA searches prior art and establishes an International Search Report (ISR) with written opinion on patentability.", keywords:["search","ISA","prior art","ISR","written opinion"] },
      { section:"PCT Art. 33", title:"Preliminary Examination", summary:"The IPEA examines whether the invention appears novel, involves an inventive step, and is industrially applicable.", keywords:["examination","IPEA","novelty","inventive","industrial"] },
    ],
    filingRequirements:[
      "PCT Request form (PCT/RO/101)",
      "Description, Claims, Abstract, Drawings",
      "Filing in one of 10 accepted languages",
      "International filing fee",
      "Designation of target countries",
      "National phase entry within 30 months",
    ],
  },
};

// ── USPTO template sections ───────────────────────────────────────────────────
const USPTO_TEMPLATE = {
  sections:[
    { id:"title",       label:"TITLE OF INVENTION",              required:true,  maxWords:15,  guidance:"Brief, specific title (max 15 words). No tradenames. Example: 'Rotational Stabilization Mechanism for Cylindrical Objects'" },
    { id:"crossRef",    label:"CROSS-REFERENCE TO RELATED APPS", required:false,               guidance:"Reference pending related applications. If none: write 'Not Applicable'" },
    { id:"field",       label:"FIELD OF THE INVENTION",          required:true,                guidance:"One paragraph on the technical field. Start: 'The present invention relates to...'" },
    { id:"background",  label:"BACKGROUND OF THE INVENTION",     required:true,                guidance:"Describe prior art and its deficiencies. End with the problem your invention solves. Do NOT admit your invention is prior art." },
    { id:"summary",     label:"SUMMARY OF THE INVENTION",        required:true,                guidance:"Brief statement mirroring your broadest claim. Start: 'In one embodiment, the invention provides...'" },
    { id:"drawings",    label:"BRIEF DESCRIPTION OF DRAWINGS",   required:false,               guidance:"List each figure. 'FIG. 1 is a perspective view of...' Required only if drawings submitted." },
    { id:"description", label:"DETAILED DESCRIPTION",            required:true,                guidance:"Full enabling disclosure. Describe best mode. Reference all drawing figures. Must enable a PHOSITA to make and use the invention." },
    { id:"claims",      label:"CLAIMS",                          required:true,                guidance:"At least 1 independent claim. Single-sentence format starting: 'A [device/method/system] comprising:'. Each element on new line with semicolons." },
    { id:"abstract",    label:"ABSTRACT OF THE DISCLOSURE",      required:true,  maxWords:150, guidance:"Single paragraph 50-150 words. Do NOT reference drawings. Start: 'A [device/method]...' Summarize invention and main advantages." },
  ],
};

// ── Prosecution stages ────────────────────────────────────────────────────────
const PROSECUTION_STAGES = [
  { id:"filed",       label:"Filed",             color:"#5b4bdb", days:0 },
  { id:"published",   label:"Published",         color:"#00c9f5", days:548 },
  { id:"examination", label:"Examination",        color:"#f5a623", days:730 },
  { id:"oa1",         label:"Office Action 1",   color:"#f5365c", days:900 },
  { id:"response",    label:"Response Filed",    color:"#00d47e", days:990 },
  { id:"allowance",   label:"Allowance",         color:"#00d47e", days:1095 },
  { id:"granted",     label:"Granted",           color:"#f0c040", days:1200 },
];

function calcDeadlines(filingDate) {
  const base = new Date(filingDate);
  return [
    { label:"Publication",        date:new Date(base.getTime()+548*86400000).toISOString().slice(0,10), note:"18 months from filing" },
    { label:"Prosecution Deadline",date:new Date(base.getTime()+730*86400000).toISOString().slice(0,10), note:"2 years" },
    { label:"3.5yr Maintenance",  date:new Date(base.getTime()+1277*86400000).toISOString().slice(0,10), note:"First maintenance fee" },
    { label:"7.5yr Maintenance",  date:new Date(base.getTime()+2738*86400000).toISOString().slice(0,10), note:"Second maintenance fee" },
    { label:"11.5yr Maintenance", date:new Date(base.getTime()+4199*86400000).toISOString().slice(0,10), note:"Third maintenance fee" },
    { label:"Patent Expiry",      date:new Date(base.getTime()+7305*86400000).toISOString().slice(0,10), note:"20 years from filing date" },
  ];
}

// ── Semantic clusters ─────────────────────────────────────────────────────────
const CLUSTERS = {
  motion:["roll","tumble","rotate","spin","revolve","gyrate","pivot","turn","wheel"],
  locomotion:["locomotion","movement","travel","navigate","propel","transport","translate"],
  document:["document","text","file","record","paper","annotation","writing","draft","patent","claim"],
  detect:["detect","identify","find","recognize","analyze","scan","search","match"],
  energy:["energy","power","electricity","harvest","solar","battery","charge","photovoltaic"],
  network:["network","distributed","blockchain","ledger","decentralized","node","protocol"],
  neural:["neural","learning","intelligence","machine","model","deep","predict","inference"],
  haptic:["haptic","tactile","touch","vibration","sensation","feedback","actuator"],
  aerial:["aerial","drone","uav","flight","airborne","lidar","quadcopter","unmanned"],
  bio:["biodegradable","organic","eco","green","sustainable","compost","plant","waste"],
  vision:["vision","camera","image","visual","optical","pixel","sensor","capture"],
  storage:["storage","memory","cache","database","flash","persist","archive"],
  security:["security","encrypt","authentication","certificate","hash","verify"],
  medical:["medical","drug","pharmaceutical","therapy","treatment","diagnosis","clinical"],
  wireless:["wireless","radio","bluetooth","wifi","signal","antenna","transmit"],
  mechanical:["gear","spring","piston","valve","torque","bearing","shaft","rotor"],
  chemical:["catalyst","polymer","synthesis","solvent","oxide","alloy","composite"],
};
function getCluster(w) {
  const word=w.toLowerCase();
  for(const [c,ws] of Object.entries(CLUSTERS)) if(ws.some(k=>word.includes(k)||k.includes(word))) return c;
  return null;
}
function semanticScore(inputText, patent) {
  const iW=inputText.toLowerCase().split(/\W+/).filter(w=>w.length>3);
  const pW=(patent.title+" "+patent.abstract).toLowerCase().split(/\W+/).filter(w=>w.length>3);
  const iS=new Set(iW),pS=new Set(pW);
  let ex=0; for(const w of iS) if(pS.has(w)) ex++;
  const iC=new Set(iW.map(getCluster).filter(Boolean));
  const pC=new Set(pW.map(getCluster).filter(Boolean));
  let sc=0; for(const c of iC) if(pC.has(c)) sc++;
  return Math.min(1,(ex/Math.max(iS.size,1))*0.55+(sc/Math.max(Math.max(iC.size,pC.size),1))*0.65);
}

// ── Tokenizer ─────────────────────────────────────────────────────────────────
const SW=new Set(["the","a","an","and","or","but","in","on","at","to","for","of","with","by","from","is","are","was","were","be","been","have","has","had","do","does","did","will","would","could","should","may","might","this","that","these","those","it","its","not","no","as","than","more","some","any","all","so","very","just","also","then","when","where","which","who","what"]);
function tokenize(raw) {
  if(!raw?.trim()) return {tokens:[],topKeywords:[],bigrams:[],clusters:[],sections:[],claims:[],stats:{}};
  const t0=performance.now();
  const clean=raw.replace(/[^\x20-\x7E\n]/g," ").replace(/\s+/g," ").trim();
  const sents=clean.split(/(?<=[.!?])\s+(?=[A-Z])/).filter(s=>s.length>10);
  const all=clean.toLowerCase().split(/\W+/).filter(w=>w.length>2);
  const toks=all.filter(w=>!SW.has(w));
  const freq={}; for(const t of toks) freq[t]=(freq[t]||0)+1;
  const topKeywords=Object.entries(freq).sort((a,b)=>b[1]-a[1]).slice(0,25).map(([word,count])=>({word,count}));
  const bg={}; for(let i=0;i<toks.length-1;i++){const k=`${toks[i]} ${toks[i+1]}`;bg[k]=(bg[k]||0)+1;}
  const bigrams=Object.entries(bg).filter(([,c])=>c>1).sort((a,b)=>b[1]-a[1]).slice(0,12).map(([phrase,count])=>({phrase,count}));
  const cm={}; for(const t of toks){const c=getCluster(t);if(c)cm[c]=(cm[c]||0)+1;}
  const clusters=Object.entries(cm).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([name,count])=>({name,count}));
  const sRe={Abstract:/\babstract\s*[:\-\n]/i,Background:/\bbackground\s*[:\-\n]/i,Claims:/\bclaims?\s*[:\-\n]/i,Summary:/\bsummary\s*[:\-\n]/i};
  const sections=Object.entries(sRe).filter(([,re])=>re.test(clean)).map(([n])=>n);
  const claims=sents.filter(s=>/\bwherein\b|\bcomprising\b|\bconsisting\b/i.test(s)).slice(0,8);
  return {clean:clean.slice(0,4000),tokens:toks,topKeywords,bigrams,clusters,sections,claims,stats:{chars:raw.length,words:all.length,uniqueWords:Object.keys(freq).length,sentences:sents.length,tokens:toks.length,claims:claims.length,processMs:(performance.now()-t0).toFixed(1)}};
}

// ── Global ledger (shared:true = all users see it) ────────────────────────────
async function ledgerAdd(entry) {
  try {
    const idx=await store.get("ledger:index",true).catch(()=>null);
    const index=idx?JSON.parse(idx.value):[];
    if(!index.includes(entry.id)) index.push(entry.id);
    await store.set(`ledger:${entry.id}`,JSON.stringify(entry),true);
    await store.set("ledger:index",JSON.stringify(index),true);
    return true;
  } catch(e){console.error(e);return false;}
}
async function ledgerGetAll() {
  try {
    const idx=await store.get("ledger:index",true).catch(()=>null);
    if(!idx) return [];
    const ids=JSON.parse(idx.value);
    const entries=await Promise.all(ids.map(id=>store.get(`ledger:${id}`,true).then(r=>r?JSON.parse(r.value):null).catch(()=>null)));
    return entries.filter(Boolean).sort((a,b)=>b.timestamp-a.timestamp);
  } catch {return [];}
}
async function ledgerVerify(id) {
  try {
    const r=await store.get(`ledger:${id}`,true);
    if(!r) return {verified:false,reason:"Not found in ledger"};
    const entry=JSON.parse(r.value);
    const result=await verifyLedgerEntry(entry);
    return {...result, entry};
  } catch(e){return {verified:false,reason:e.message};}
}

// ══════════════════════════════════════════════════════════════════════════════
//  PENDING VAULT — timed publication system (35 USC §122)
//  Patents stored here until their locked publication date arrives,
//  then auto-released to global ledger in bulk.
// ══════════════════════════════════════════════════════════════════════════════

// Publication schedule options
const PUB_SCHEDULES = [
  { id:"immediate",  label:"Immediate",           months:0,  note:"Released as soon as verification completes" },
  { id:"early6",     label:"6 months",            months:6,  note:"Early publication — establishes prior art sooner" },
  { id:"early12",    label:"12 months",            months:12, note:"Early publication" },
  { id:"standard",   label:"18 months (Standard)", months:18, note:"Legal default under 35 USC §122(b)" },
];

function calcPublicationDate(filingTimestamp, months) {
  if (months === 0) return filingTimestamp; // immediate
  const d = new Date(filingTimestamp);
  d.setMonth(d.getMonth() + months);
  return d.getTime();
}

async function pendingVaultAdd(entry) {
  try {
    const idx   = await store.get("pendingvault:index", true).catch(() => null);
    const index = idx ? JSON.parse(idx.value) : [];
    if (!index.includes(entry.id)) index.push(entry.id);
    await store.set(`pendingvault:${entry.id}`, JSON.stringify(entry), true);
    await store.set("pendingvault:index", JSON.stringify(index), true);
    return true;
  } catch(e) { console.error(e); return false; }
}

async function pendingVaultGetAll() {
  try {
    const idx = await store.get("pendingvault:index", true).catch(() => null);
    if (!idx) return [];
    const ids = JSON.parse(idx.value);
    const entries = await Promise.all(ids.map(id =>
      store.get(`pendingvault:${id}`, true).then(r => r ? JSON.parse(r.value) : null).catch(() => null)
    ));
    return entries.filter(Boolean).sort((a,b) => a.publicationDate - b.publicationDate);
  } catch { return []; }
}

async function pendingVaultRemove(id) {
  try {
    await store.delete(`pendingvault:${id}`, true);
    const idx   = await store.get("pendingvault:index", true).catch(() => null);
    if (!idx) return;
    const index = JSON.parse(idx.value).filter(i => i !== id);
    await store.set("pendingvault:index", JSON.stringify(index), true);
  } catch {}
}

// Auto-release: check pending vault on app load and release expired entries
async function checkAndReleaseDuePatents(onRelease) {
  const now     = Date.now();
  const pending = await pendingVaultGetAll();
  const due     = pending.filter(e => e.publicationDate <= now);
  if (due.length === 0) return 0;
  for (const entry of due) {
    await ledgerAdd({ ...entry, releasedAt: now, releaseType: "scheduled" });
    await pendingVaultRemove(entry.id);
  }
  if (onRelease && due.length > 0) onRelease(due);
  return due.length;
}

// ── Unified storage adapter ──────────────────────────────────────────────────
// Imported from ./lib/store (Supabase when VITE_SUPABASE_* are set, else localStorage).

// ── Submit to government pending queue ───────────────────────────────────────
// Writes to shared pending:* storage so GovPortal can read it immediately
async function submitToGovQueue(submission) {
  try {
    const idx   = await store.get("pending:index", true);
    const index = idx ? JSON.parse(idx.value) : [];
    if (!index.includes(submission.id)) index.push(submission.id);
    await store.set(`pending:${submission.id}`, JSON.stringify(submission), true);
    await store.set("pending:index", JSON.stringify(index), true);
    return true;
  } catch(e) { console.error("submitToGovQueue error:", e); return false; }
}

// ── Personal vault ────────────────────────────────────────────────────────────
async function vaultSave(doc) {
  try {
    const idx=await store.get("vault:index").catch(()=>null);
    const index=idx?JSON.parse(idx.value):[];
    if(!index.includes(doc.id)) index.push(doc.id);
    await store.set(`vault:${doc.id}`,JSON.stringify(doc));
    await store.set("vault:index",JSON.stringify(index));
    return true;
  } catch {return false;}
}
async function vaultGetAll() {
  try {
    const idx=await store.get("vault:index").catch(()=>null);
    if(!idx) return [];
    const ids=JSON.parse(idx.value);
    const docs=await Promise.all(ids.map(id=>store.get(`vault:${id}`).then(r=>r?JSON.parse(r.value):null).catch(()=>null)));
    return docs.filter(Boolean);
  } catch {return [];}
}
async function vaultDelete(id) {
  try {
    await store.delete(`vault:${id}`);
    const idx=await store.get("vault:index").catch(()=>null);
    if(!idx) return;
    const index=JSON.parse(idx.value).filter(i=>i!==id);
    await store.set("vault:index",JSON.stringify(index));
  } catch {}
}

// Read all pending (government-queue) applications so the user app can show
// each vault item's live status (submitted / withdrawable / on-ledger).
async function pendingGetAll() {
  try {
    const idx=await store.get("pending:index",true).catch(()=>null);
    if(!idx) return [];
    const ids=JSON.parse(idx.value);
    const apps=await Promise.all(ids.map(id=>store.get(`pending:${id}`,true).then(r=>r?JSON.parse(r.value):null).catch(()=>null)));
    return apps.filter(Boolean);
  } catch { return []; }
}

// Withdraw a not-yet-granted submission from the government queue (the safe
// "unwind" before grant). Removes it from the pending queue and marks the vault
// copy WITHDRAWN. NOT allowed once the patent is on the immutable ledger.
async function withdrawSubmission(id) {
  try {
    await store.delete(`pending:${id}`,true);
    const idx=await store.get("pending:index",true).catch(()=>null);
    if(idx){
      const index=JSON.parse(idx.value).filter(i=>i!==id);
      await store.set("pending:index",JSON.stringify(index),true);
    }
    // mark the vault copy as withdrawn (keep the file; it's just out of the queue)
    const v=await store.get(`vault:${id}`).catch(()=>null);
    if(v){ const doc=JSON.parse(v.value); doc.status="WITHDRAWN"; await store.set(`vault:${id}`,JSON.stringify(doc)); }
    return true;
  } catch(e){ console.error("withdrawSubmission error:",e); return false; }
}

// ── USPTO + Claude ────────────────────────────────────────────────────────────
async function searchUSPTO(query,perPage=30) {
  try {
    const res=await fetch(`${API_BASE}/uspto/search?q=${encodeURIComponent(query)}&per_page=${perPage}`,{headers:FORM_HEADERS});
    if(!res.ok) throw new Error("backend");
    return (await res.json()).patents||[];
  } catch {
    const p=new URLSearchParams({q:JSON.stringify({_text_any:{patent_abstract:query}}),f:JSON.stringify(["patent_id","patent_title","patent_abstract","patent_date","assignee_organization"]),o:JSON.stringify({size:perPage,sort:[{patent_date:"desc"}]})});
    const r=await fetch(`https://search.patentsview.org/api/v1/patent/?${p}`,{headers:{Accept:"application/json"}});
    const d=await r.json();
    return (d.patents||[]).map(p=>({id:`US${p.patent_id}`,title:p.patent_title||"",abstract:(p.patent_abstract||"").slice(0,400),year:p.patent_date?parseInt(p.patent_date):null,assignee:p.assignee_organization||"—",url:`https://patents.google.com/patent/US${p.patent_id}`,source:"uspto"})).filter(p=>p.abstract.length>40);
  }
}
async function callClaude(messages,system) {
  // Calls the backend proxy (/claude) so the Anthropic API key stays server-side.
  const resp=await fetch(`${API_BASE}/claude`,{method:"POST",headers:FETCH_HEADERS,body:JSON.stringify({system,messages})});
  if(!resp.ok) return "";
  const d=await resp.json();
  return d.text||d.content?.find(b=>b.type==="text")?.text||"";
}
async function analyzePatent(text,results,jurisdiction="US") {
  const laws=JURISDICTIONS[jurisdiction]?.laws.slice(0,3).map(l=>`${l.section}: ${l.summary}`).join("\n")||"";
  const system=`You are PatentGuard AI, expert patent attorney. Return ONLY raw JSON:\n{"assessment":"2-3 sentence risk summary","overlaps":["overlapping claim"],"verdict":"SAFE"|"CAUTION"|"HIGH RISK","verdictReason":"one sentence","suggestions":["differentiation idea"],"legalIssues":["law section concern"]}\nRelevant law:\n${laws}`;
  try {
    const raw=await callClaude([{role:"user",content:`Invention:\n"${text.slice(0,600)}"\n\nSimilar patents:\n${results.slice(0,3).map(p=>`[${p.id}] ${p.title}\n${p.abstract.slice(0,120)}`).join("\n\n")}`}],system);
    return JSON.parse(raw.replace(/```json|```/g,"").trim());
  } catch {return {assessment:"Analysis unavailable.",overlaps:[],verdict:"CAUTION",verdictReason:"Could not parse.",suggestions:[],legalIssues:[]};}
}

// ── Design tokens ─────────────────────────────────────────────────────────────
const C={bg:"#06060f",panel:"#0c0c1e",border:"#13132a",accent:"#5b4bdb",cyan:"#00c9f5",green:"#00d47e",amber:"#f5a623",red:"#f5365c",text:"#e8e8f8",muted:"#343460",dim:"#1a1a32",gold:"#f0c040"};

// ── UI primitives ─────────────────────────────────────────────────────────────
function Pill({color,children,small,onClick}){return <span onClick={onClick} style={{display:"inline-flex",alignItems:"center",gap:4,padding:small?"2px 7px":"4px 11px",borderRadius:20,background:`${color}18`,border:`1px solid ${color}35`,fontSize:small?9:11,color,fontWeight:700,letterSpacing:"0.06em",fontFamily:"monospace",cursor:onClick?"pointer":"default"}}>{children}</span>;}
function Badge({color,icon,label}){return <span style={{display:"inline-flex",alignItems:"center",gap:5,padding:"3px 10px",borderRadius:4,background:`${color}18`,border:`1px solid ${color}40`,fontSize:11,color,fontWeight:700,letterSpacing:"0.07em"}}>{icon} {label}</span>;}
function ScoreBar({score,height=4}){const pct=Math.round(score*100);const col=pct>65?C.red:pct>35?C.amber:C.green;return <div style={{display:"flex",alignItems:"center",gap:8}}><div style={{flex:1,height,background:C.dim,borderRadius:3,overflow:"hidden"}}><div style={{width:`${pct}%`,height:"100%",background:col,borderRadius:3,transition:"width 0.5s"}}/></div><span style={{fontSize:11,color:col,fontWeight:700,minWidth:32,fontFamily:"monospace"}}>{pct}%</span></div>;}
function Spinner({size=12}){return <span style={{display:"inline-block",width:size,height:size,border:`2px solid ${C.accent}40`,borderTopColor:C.accent,borderRadius:"50%",animation:"spin 0.7s linear infinite"}}/>;}
function PGInput({value,onChange,placeholder,onKeyDown,style={}}){return <input value={value} onChange={onChange} onKeyDown={onKeyDown} placeholder={placeholder} style={{background:C.panel,border:`1px solid ${C.border}`,color:C.text,fontFamily:"monospace",fontSize:12,padding:"7px 12px",borderRadius:6,outline:"none",...style}} onFocus={e=>e.target.style.borderColor=`${C.accent}60`} onBlur={e=>e.target.style.borderColor=C.border}/>;}
function Btn({children,onClick,disabled,color,small,style={}}){const bg=color||C.accent;return <button onClick={onClick} disabled={disabled} style={{background:`${bg}22`,border:`1px solid ${bg}50`,color:bg,fontFamily:"monospace",fontSize:small?10:11,padding:small?"4px 10px":"7px 16px",borderRadius:6,cursor:"pointer",transition:"all 0.2s",letterSpacing:"0.07em",opacity:disabled?0.35:1,...style}}>{children}</button>;}

// ══════════════════════════════════════════════════════════════════════════════
//  CHAT BOT
// ══════════════════════════════════════════════════════════════════════════════
function ChatBot({ledger,jurisdiction,setJurisdiction}){
  const [msgs,setMsgs]=useState([{role:"assistant",content:`Hello! I'm PatentGuard AI — your patent attorney assistant.\n\nI have access to:\n• Global Patent Ledger (${ledger.length} verified patents)\n• Jurisdictional Laws: US USPTO, EU EPO, PCT/WIPO\n• USPTO Filing Format & Templates\n• Live USPTO prior art database\n\nAsk me to:\n— Draft patent claims for your invention\n— Check §101/§102/§103/§112 compliance\n— Format your full patent application\n— Explain filing requirements & fees\n— Analyze prior art conflict risk`}]);
  const [input,setInput]=useState("");
  const [loading,setLoading]=useState(false);
  const bottomRef=useRef();
  useEffect(()=>{bottomRef.current?.scrollIntoView({behavior:"smooth"});},[msgs]);

  const send=async()=>{
    if(!input.trim()||loading) return;
    const userMsg={role:"user",content:input};
    setMsgs(prev=>[...prev,userMsg]); setInput(""); setLoading(true);
    const jur=JURISDICTIONS[jurisdiction];
    const laws=jur?.laws.map(l=>`${l.section} (${l.title}): ${l.summary}`).join("\n")||"";
    const ledgerSummary=ledger.slice(0,5).map(e=>`[${e.id}] ${e.title}`).join("\n")||"No patents yet.";
    const templateSections=USPTO_TEMPLATE.sections.map(s=>`${s.label}: ${s.guidance}`).join("\n");
    const system=`You are PatentGuard AI, expert patent attorney embedded in the PatentGuard platform.

CURRENT JURISDICTION: ${jur?.name||"US USPTO"}

PATENT LAW:
${laws}

GLOBAL LEDGER (recent entries):
${ledgerSummary}

USPTO FORMAT GUIDANCE:
${templateSections}

FILING REQUIREMENTS:
${jur?.filingRequirements?.join("; ")||""}

Guidelines: Be specific and legally accurate. Cite law sections (35 USC §102 etc). Use proper patent claim language (comprising, wherein, configured to). Flag §101/§102/§103/§112 issues. Mention fees and deadlines. Draft properly formatted patent text when asked.`;
    const history=msgs.slice(-8).concat(userMsg).map(m=>({role:m.role,content:m.content}));
    try {
      const reply=await callClaude(history,system);
      setMsgs(prev=>[...prev,{role:"assistant",content:reply}]);
    } catch(e){setMsgs(prev=>[...prev,{role:"assistant",content:`Error: ${e.message}`}]);}
    finally{setLoading(false);}
  };

  const quickPrompts=["Draft independent claims for a machine learning patent","What are the §101 eligibility requirements?","Help me write an abstract under 150 words","Check if my invention meets novelty requirements","Explain the difference between utility and design patents","What PCT countries should I file in?"];

  return (
    <div style={{display:"flex",flexDirection:"column",height:"100%"}}>
      <div style={{padding:"8px 14px",borderBottom:`1px solid ${C.border}`,display:"flex",gap:6,alignItems:"center",flexShrink:0}}>
        <span style={{fontSize:10,color:C.muted,letterSpacing:"0.1em"}}>JURISDICTION:</span>
        {Object.values(JURISDICTIONS).map(j=><Btn key={j.code} onClick={()=>setJurisdiction(j.code)} small color={jurisdiction===j.code?C.accent:C.muted}>{j.flag} {j.code}</Btn>)}
      </div>
      <div style={{flex:1,overflowY:"auto",padding:"14px",display:"flex",flexDirection:"column",gap:8}}>
        {msgs.map((m,i)=>(
          <div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start"}}>
            <div style={{maxWidth:"88%",padding:"10px 14px",borderRadius:m.role==="user"?"12px 12px 2px 12px":"2px 12px 12px 12px",background:m.role==="user"?`${C.accent}22`:C.panel,border:`1px solid ${m.role==="user"?C.accent+"40":C.border}`,fontSize:12,color:C.text,lineHeight:1.75,whiteSpace:"pre-wrap",fontFamily:"monospace"}}>
              {m.role==="assistant"&&<span style={{fontSize:9,color:C.accent,letterSpacing:"0.1em",display:"block",marginBottom:4}}>⚡ PATENTGUARD AI · {JURISDICTIONS[jurisdiction]?.flag} {jurisdiction}</span>}
              {m.content}
            </div>
          </div>
        ))}
        {loading&&<div style={{display:"flex"}}><div style={{padding:"10px 14px",borderRadius:"2px 12px 12px 12px",background:C.panel,border:`1px solid ${C.border}`,display:"flex",alignItems:"center",gap:8}}><Spinner/><span style={{fontSize:11,color:C.muted}}>Consulting patent databases...</span></div></div>}
        <div ref={bottomRef}/>
      </div>
      <div style={{padding:"6px 14px",borderTop:`1px solid ${C.border}`,display:"flex",flexWrap:"wrap",gap:4,flexShrink:0}}>
        {quickPrompts.map(p=><button key={p} onClick={()=>setInput(p)} style={{background:C.dim,border:`1px solid ${C.border}`,color:C.muted,fontSize:10,padding:"3px 8px",borderRadius:4,cursor:"pointer",fontFamily:"monospace"}}>{p}</button>)}
      </div>
      <div style={{padding:"10px 14px",borderTop:`1px solid ${C.border}`,display:"flex",gap:8,flexShrink:0}}>
        <PGInput value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&!e.shiftKey&&send()} placeholder="Ask about patent law, draft claims, check compliance..." style={{flex:1}}/>
        <Btn onClick={send} disabled={loading||!input.trim()}>{loading?<Spinner/>:"SEND →"}</Btn>
      </div>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
//  UPLOAD PANEL (gov code + ZK + IPFS)
// ══════════════════════════════════════════════════════════════════════════════
function UploadPanel(){
  // State
  const [file,        setFile]        = useState(null);
  const [over,        setOver]        = useState(false);
  const [userKey,     setUserKey]     = useState("");
  const [pubSchedule, setPubSchedule] = useState("standard");
  const [status,      setStatus]      = useState(null); // null|"processing"|"sent"|"error"
  const [msg,         setMsg]         = useState("");
  const [submittedId, setSubmittedId] = useState(null);
  const [demoKey,     setDemoKey]     = useState("");
  const inputRef = useRef();

  // ── When file is dropped, auto-generate user key from content ────────────────
  const handleFile = async (f) => {
    if (!f) return;
    setFile(f); setStatus("processing"); setMsg(`Reading ${f.name}...`);
    try {
      const text = await new Promise((res,rej)=>{
        const r=new FileReader();
        r.onload=e=>res(e.target.result);
        r.onerror=()=>rej(new Error("File read error"));
        r.readAsText(f);
      });
      const key = await generateUserKey(text, Date.now());
      setUserKey(key);
      setStatus(null); setMsg("");
    } catch(e) { setStatus("error"); setMsg(`✗ ${e.message}`); }
  };

  // ── Send to Government ────────────────────────────────────────────────────────
  const handleSend = async () => {
    if (!file || !userKey) return;
    setStatus("processing"); setMsg("Generating ZK commitment...");
    try {
      // Extract real text (pdf.js for PDFs; direct read for text files).
      // Scanned/image PDFs have no text layer and fall back to OCR, which is
      // slow — surface per-page progress so the user knows it's working.
      const rawText = await extractFileText(file, {
        onProgress: ({ stage, page, pages }) => {
          if (stage === "ocr") setMsg(`Scanned PDF detected — running OCR (page ${page}/${pages})...`);
        },
      });
      if (!rawText || rawText.trim().length < 20) {
        throw new Error("Could not extract text from this file. For scanned/image PDFs, paste the text via the template editor instead.");
      }

      const salt      = Array.from(crypto.getRandomValues(new Uint8Array(16))).join("");
      const zk        = await zkCommit(rawText, salt);

      setMsg("Tokenizing document...");
      const td        = tokenize(rawText);

      setMsg("Assigning IPFS content ID...");
      const ipfsCid   = await generateIPFSCid(rawText);

      const timestamp = Date.now();
      const entryId   = `PG-${timestamp.toString(36).toUpperCase()}`;
      const firstLine = rawText.split("\n").find(l=>l.trim().length>10)||"";
      const title     = firstLine.slice(0,80)||td.topKeywords.slice(0,3).map(k=>k.word).join(" ")||file.name;

      // Chosen publication schedule — locked here, immutable after submission
      const sched     = PUB_SCHEDULES.find(s=>s.id===pubSchedule)||PUB_SCHEDULES[3];

      const submission = {
        id:               entryId,
        title,
        fileName:         file.name,
        userKey,                          // applicant key — gov derives their key from this
        contentHash:      zk.contentHash,
        ipfsCid,
        zkCommitment:     zk.commitment,
        zkNullifier:      zk.nullifier,
        zkBindingKey:     zk.bindingKey,
        zkSalt:           zk.salt,
        proofType:        zk.proofType,
        publicationSchedule: sched.id,
        publicationMonths:   sched.months,
        timestamp,
        submittedAt:      new Date().toISOString(),
        status:           "SUBMITTED",
        source:           "user_portal",
        tokenData:        td,
        abstract:         td.clean.slice(0,300),
        keywords:         td.topKeywords.slice(0,8).map(k=>k.word),
        institution:      "PatentGuard User Submission",
      };

      setMsg("Sending to Government Portal...");
      const ok = await submitToGovQueue(submission);
      if (!ok) throw new Error("Failed to write to shared storage");

      // Save copy to personal vault so user can track it
      await vaultSave(submission);

      setStatus("sent");
      setSubmittedId(entryId);
      setMsg(`✓ Sent to Government Portal — Application ID: ${entryId}`);
      setFile(null); setUserKey(""); setPubSchedule("standard");
    } catch(e) { setStatus("error"); setMsg(`✗ ${e.message}`); }
  };

  const schedColor = (id) => pubSchedule===id ? C.gold : C.muted;

  return (
    <div style={{padding:20,overflowY:"auto",flex:1}}>
      <div style={{fontFamily:"monospace",fontSize:15,fontWeight:700,marginBottom:4}}>Submit Patent to Government</div>
      <div style={{fontSize:11,color:C.muted,marginBottom:20,lineHeight:1.85}}>
        Drop your patent file below. PatentGuard automatically generates your unique User Key from the document content,
        creates a zero-knowledge proof, and sends everything directly to the Government Portal for review.
        You do not need to enter any codes — the government handles the rest.
      </div>

      {/* Submitted confirmation */}
      {status==="sent"&&submittedId&&(
        <div style={{padding:"16px",background:`${C.green}12`,border:`1px solid ${C.green}40`,borderRadius:10,marginBottom:16}}>
          <div style={{fontSize:13,color:C.green,fontWeight:700,marginBottom:6}}>✓ Application Submitted to Government Portal</div>
          <div style={{fontSize:11,color:C.muted,lineHeight:1.8}}>
            Application ID: <span style={{color:C.accent,fontFamily:"monospace"}}>{submittedId}</span><br/>
            The government examiner will run a formality check, verify fees, and review your claims.<br/>
            Once approved, they will publish the patent directly to the global ledger on your chosen schedule.<br/>
            Track your submission status in the <strong>Vault</strong> tab.
          </div>
        </div>
      )}

      {/* STEP 1 — Drop file */}
      <div style={{padding:"14px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,marginBottom:12}}>
        <div style={{fontSize:10,color:C.accent,letterSpacing:"0.12em",fontWeight:700,marginBottom:8}}>
          STEP 1 — DROP YOUR PATENT FILE
        </div>
        <div
          onDragOver={e=>{e.preventDefault();setOver(true);}}
          onDragLeave={()=>setOver(false)}
          onDrop={e=>{e.preventDefault();setOver(false);handleFile(e.dataTransfer.files[0]);}}
          onClick={()=>inputRef.current?.click()}
          style={{border:`2px dashed ${over?C.accent:file?C.green:C.muted}`,borderRadius:8,padding:"20px",textAlign:"center",cursor:"pointer",background:over?`${C.accent}08`:file?`${C.green}06`:"transparent",transition:"all 0.2s",marginBottom:file?10:0}}
        >
          <input ref={inputRef} type="file" accept=".txt,.md,.pdf,.docx" style={{display:"none"}} onChange={e=>handleFile(e.target.files[0])}/>
          <div style={{fontSize:26,marginBottom:6}}>{file?"📄":"📂"}</div>
          <div style={{fontSize:12,color:file?C.green:C.text,fontFamily:"monospace"}}>
            {file?`✓ ${file.name} (${(file.size/1024).toFixed(0)}KB)`:"Drop patent file here or click to browse"}
          </div>
          <div style={{fontSize:10,color:C.muted,marginTop:3}}>.TXT · .PDF · .DOCX · .MD — Max 10MB</div>
        </div>

        {/* Auto-generated user key */}
        {userKey&&(
          <div style={{padding:"10px 12px",background:`${C.accent}12`,border:`1px solid ${C.accent}40`,borderRadius:8}}>
            <div style={{fontSize:9,color:C.accent,letterSpacing:"0.12em",marginBottom:4,fontWeight:700}}>
              YOUR USER KEY — AUTO-GENERATED FROM DOCUMENT CONTENT
            </div>
            <div style={{fontSize:12,fontFamily:"monospace",color:C.accent,letterSpacing:"0.06em",wordBreak:"break-all",marginBottom:4}}>
              {userKey}
            </div>
            <div style={{fontSize:10,color:C.muted,lineHeight:1.6}}>
              This key is derived from your document's SHA-256 hash + timestamp. It uniquely identifies your authorship.
              The government will derive their matching key from this key — you do not need to enter anything else.
            </div>
          </div>
        )}
      </div>

      {/* STEP 2 — Publication schedule */}
      <div style={{padding:"14px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,marginBottom:12}}>
        <div style={{fontSize:10,color:C.gold,letterSpacing:"0.12em",fontWeight:700,marginBottom:8}}>
          📅 STEP 2 — CHOOSE PUBLICATION SCHEDULE (35 USC §122)
        </div>
        <div style={{fontSize:10,color:C.muted,marginBottom:10,lineHeight:1.7}}>
          This date is locked and immutable once you submit. The government will publish your patent to the global ledger on this schedule.
        </div>
        <div style={{display:"flex",flexDirection:"column",gap:6}}>
          {PUB_SCHEDULES.map(s=>(
            <div key={s.id} onClick={()=>setPubSchedule(s.id)} style={{padding:"9px 12px",borderRadius:7,cursor:"pointer",
              background:pubSchedule===s.id?`${C.gold}15`:C.dim,
              border:`1px solid ${pubSchedule===s.id?C.gold+"60":C.border}`,transition:"all 0.2s"}}>
              <div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}>
                <span style={{fontSize:12,color:pubSchedule===s.id?C.gold:C.text,fontWeight:pubSchedule===s.id?700:400}}>
                  {pubSchedule===s.id?"● ":"○ "}{s.label}
                  {s.id==="standard"&&<span style={{fontSize:9,color:C.accent,marginLeft:8,fontFamily:"monospace"}}>LEGAL DEFAULT</span>}
                </span>
                {pubSchedule===s.id&&s.months>0&&(
                  <span style={{fontSize:10,color:C.gold,fontFamily:"monospace"}}>
                    {new Date(calcPublicationDate(Date.now(),s.months)).toLocaleDateString()}
                  </span>
                )}
              </div>
              <div style={{fontSize:10,color:C.muted,marginTop:2}}>{s.note}</div>
            </div>
          ))}
        </div>
      </div>

      {/* STEP 3 — Send button */}
      <Btn onClick={handleSend} disabled={!file||!userKey||status==="processing"}
        style={{width:"100%",padding:"12px",justifyContent:"center",display:"flex",alignItems:"center",gap:8,fontSize:13}}>
        {status==="processing"?<><Spinner/> {msg}</>:"📤 SEND TO GOVERNMENT PORTAL"}
      </Btn>

      {status==="error"&&(
        <div style={{marginTop:10,padding:"10px 14px",borderRadius:8,fontSize:11,color:C.red,background:`${C.red}12`,border:`1px solid ${C.red}40`}}>
          {msg}
        </div>
      )}

      {/* How it works */}
      <div style={{marginTop:14,padding:"12px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:8}}>
        <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",marginBottom:8}}>WHAT HAPPENS AFTER YOU SEND</div>
        {[
          ["🏛","Government Portal receives your file + user key instantly"],
          ["🔍","Automatic formality check — document completeness verified"],
          ["💳","Fee verification — examiner confirms payment"],
          ["📋","Human claim review — examiner evaluates each claim"],
          ["🔐","Gov key derived from your user key — cryptographic binding created"],
          ["⏳","Patent enters pending vault with your chosen publication date locked"],
          ["⛓","On publication date — auto-released to global ledger for all to see"],
        ].map(([icon,text],i)=>(
          <div key={i} style={{display:"flex",gap:8,padding:"3px 0",alignItems:"flex-start"}}>
            <span style={{fontSize:13,flexShrink:0}}>{icon}</span>
            <span style={{fontSize:11,color:C.muted,lineHeight:1.5}}>{text}</span>
          </div>
        ))}
      </div>
    </div>
  );
}


function LedgerPanel({entries}){
  const [verifying,setVerifying]=useState(null);
  const [verResult,setVerResult]=useState({});

  const verify=async(id)=>{
    setVerifying(id);
    const r=await ledgerVerify(id);
    setVerResult(prev=>({...prev,[id]:r}));
    setVerifying(null);
  };

  return (
    <div style={{padding:20,overflowY:"auto",flex:1}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}>
        <div style={{fontFamily:"monospace",fontSize:15,fontWeight:700}}>Global Patent Ledger</div>
        <Pill color={C.cyan}>{entries.length} ENTRIES</Pill>
      </div>
      <div style={{fontSize:11,color:C.muted,marginBottom:14,lineHeight:1.7}}>All patents submitted with valid government codes. Each entry is SHA-256 hashed, IPFS-indexed, and ZK-committed. Shared across all users in real time. Click VERIFY to check cryptographic integrity.</div>
      {entries.length===0?(
        <div style={{textAlign:"center",padding:"40px",color:C.muted}}>
          <div style={{fontSize:36,marginBottom:12}}>⛓</div>
          <div style={{fontSize:11,lineHeight:1.8}}>No entries yet.<br/>Upload a patent with a valid government code to begin the ledger.</div>
        </div>
      ):entries.map(e=>{
        const vr=verResult[e.id];
        return (
          <div key={e.id} style={{marginBottom:10,padding:"14px",background:C.panel,border:`1px solid ${vr?.verified===false?C.red+"40":vr?.verified?C.green+"40":C.border}`,borderRadius:10}}>
            <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}>
              <div><span style={{fontSize:10,color:C.cyan,fontFamily:"monospace",fontWeight:700}}>{e.id}</span><span style={{fontSize:9,color:C.muted,marginLeft:8,fontFamily:"monospace"}}>{new Date(e.timestamp).toLocaleDateString()}</span></div>
              <div style={{display:"flex",gap:6,alignItems:"center"}}>
                {vr&&<Badge color={vr.verified?C.green:C.red} icon={vr.verified?"✓":"✗"} label={vr.verified?"VERIFIED":"TAMPERED"}/>}
                <Btn onClick={()=>verify(e.id)} disabled={verifying===e.id} small color={C.cyan}>{verifying===e.id?<Spinner size={8}/>:"VERIFY"}</Btn>
              </div>
            </div>
            <div style={{fontSize:12,fontWeight:600,color:C.text,marginBottom:8,lineHeight:1.4}}>{e.title?.slice(0,80)}</div>
            <div style={{display:"flex",gap:5,flexWrap:"wrap",marginBottom:8}}>
              <Pill color={C.gold} small>🏛 {e.govCode}</Pill>
              <Pill color={C.cyan} small>IPFS: {e.ipfsCid?.slice(0,14)}...</Pill>
              <Pill color={C.accent} small>ZK ✓</Pill>
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:3}}>
              {[["Content Hash",e.contentHash?.slice(0,18)+"..."],["Ledger Hash",e.ledgerHash?.slice(0,18)+"..."],["IPFS CID",e.ipfsCid?.slice(0,20)+"..."],["ZK Commit",e.zkCommitment?.slice(0,18)+"..."]].map(([k,v])=>(
                <div key={k} style={{fontSize:9,fontFamily:"monospace"}}><span style={{color:C.muted}}>{k}: </span><span style={{color:C.dim}}>{v}</span></div>
              ))}
            </div>
            {vr&&<div style={{marginTop:8,fontSize:10,color:vr.verified?C.green:C.red}}>{vr.reason}</div>}
          </div>
        );
      })}
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
//  LAWS PANEL
// ══════════════════════════════════════════════════════════════════════════════
function LawsPanel({jurisdiction,setJurisdiction}){
  const jur=JURISDICTIONS[jurisdiction];
  const [expanded,setExpanded]=useState(null);
  return (
    <div style={{padding:20,overflowY:"auto",flex:1}}>
      <div style={{display:"flex",gap:6,marginBottom:14}}>
        {Object.values(JURISDICTIONS).map(j=><Btn key={j.code} onClick={()=>setJurisdiction(j.code)} color={jurisdiction===j.code?C.accent:C.muted}>{j.flag} {j.name.split(" ")[0]}</Btn>)}
      </div>
      <div style={{padding:"14px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:10,marginBottom:14}}>
        <div style={{fontSize:14,fontWeight:700,color:C.text,marginBottom:4,fontFamily:"monospace"}}>{jur.flag} {jur.name}</div>
        <div style={{fontSize:11,color:C.muted,marginBottom:8}}>{jur.authority}</div>
        <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
          <Pill color={C.cyan} small>📅 {jur.timeline}</Pill>
          {Object.entries(jur.fees).filter(([k])=>k!=="note").map(([k,v])=><Pill key={k} color={C.green} small>💰 {k}: {v}</Pill>)}
        </div>
        {jur.fees.note&&<div style={{fontSize:9,color:C.muted,marginTop:4}}>{jur.fees.note}</div>}
      </div>
      <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",marginBottom:8}}>KEY STATUTES</div>
      {jur.laws.map((law,i)=>(
        <div key={law.section} style={{marginBottom:6,borderRadius:8,overflow:"hidden",border:`1px solid ${expanded===i?C.accent+"50":C.border}`}}>
          <div onClick={()=>setExpanded(expanded===i?null:i)} style={{padding:"10px 14px",background:C.panel,cursor:"pointer",display:"flex",justifyContent:"space-between",alignItems:"center"}}>
            <div><span style={{fontSize:11,color:C.accent,fontFamily:"monospace",fontWeight:700}}>{law.section}</span><span style={{fontSize:11,color:C.text,marginLeft:10}}>{law.title}</span></div>
            <span style={{color:C.muted,fontSize:12}}>{expanded===i?"▲":"▼"}</span>
          </div>
          {expanded===i&&<div style={{padding:"10px 14px",background:`${C.accent}05`,borderTop:`1px solid ${C.border}`}}>
            <p style={{fontSize:11,color:C.muted,lineHeight:1.75,marginBottom:8}}>{law.summary}</p>
            <div style={{display:"flex",flexWrap:"wrap",gap:4}}>{law.keywords.map(k=><Pill key={k} color={C.accent} small>{k}</Pill>)}</div>
          </div>}
        </div>
      ))}
      <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",margin:"14px 0 8px"}}>FILING REQUIREMENTS</div>
      <div style={{padding:"12px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:8}}>
        {jur.filingRequirements.map((req,i)=>(
          <div key={i} style={{display:"flex",gap:8,padding:"4px 0",borderBottom:i<jur.filingRequirements.length-1?`1px solid ${C.border}`:"none"}}>
            <span style={{color:C.green,fontWeight:700,fontSize:11,flexShrink:0}}>✓</span>
            <span style={{fontSize:11,color:C.muted,lineHeight:1.6}}>{req}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
//  TEMPLATE PANEL
// ══════════════════════════════════════════════════════════════════════════════
// ══════════════════════════════════════════════════════════════════════════════
//  PROSECUTION TRACKER
// ══════════════════════════════════════════════════════════════════════════════
function TrackerPanel({ledger}){
  const [selected,setSelected]=useState(null);
  const [stage,setStage]=useState("filed");
  const [filingDate,setFilingDate]=useState(new Date().toISOString().slice(0,10));
  const pat=selected?ledger.find(e=>e.id===selected):null;
  const deadlines=pat?calcDeadlines(filingDate):[];
  const today=Date.now();
  const stageIdx=PROSECUTION_STAGES.findIndex(s=>s.id===stage);
  return (
    <div style={{display:"flex",height:"100%",overflow:"hidden"}}>
      <div style={{width:220,borderRight:`1px solid ${C.border}`,overflowY:"auto",flexShrink:0,padding:10}}>
        <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",marginBottom:8}}>SELECT PATENT</div>
        {ledger.length===0&&<div style={{fontSize:11,color:C.muted,textAlign:"center",padding:20}}>No patents in ledger yet</div>}
        {ledger.map(e=>(
          <div key={e.id} onClick={()=>setSelected(e.id)} style={{padding:"10px 12px",marginBottom:5,borderRadius:7,cursor:"pointer",background:selected===e.id?`${C.accent}15`:C.panel,border:`1px solid ${selected===e.id?C.accent+"50":C.border}`}}>
            <div style={{fontSize:10,color:C.cyan,fontFamily:"monospace",marginBottom:2}}>{e.id}</div>
            <div style={{fontSize:11,color:C.text,lineHeight:1.3}}>{e.title?.slice(0,45)}{e.title?.length>45?"...":""}</div>
          </div>
        ))}
      </div>
      <div style={{flex:1,overflowY:"auto",padding:20}}>
        {!pat?(
          <div style={{textAlign:"center",padding:"60px",color:C.muted}}><div style={{fontSize:36,marginBottom:12}}>📅</div><div style={{fontSize:11}}>Select a patent to track prosecution</div></div>
        ):(
          <>
            <div style={{marginBottom:14}}>
              <div style={{fontSize:14,fontWeight:700,color:C.text,fontFamily:"monospace",marginBottom:6}}>{pat.title?.slice(0,60)}</div>
              <div style={{display:"flex",gap:6,alignItems:"center",marginBottom:10}}>
                <Pill color={C.cyan} small>{pat.id}</Pill>
                <Pill color={C.gold} small>🏛 {pat.govCode}</Pill>
              </div>
              <div style={{display:"flex",gap:8,alignItems:"center"}}>
                <span style={{fontSize:10,color:C.muted}}>FILING DATE:</span>
                <PGInput value={filingDate} onChange={e=>setFilingDate(e.target.value)} style={{width:140}}/>
              </div>
            </div>
            <div style={{marginBottom:20}}>
              <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",marginBottom:12}}>PROSECUTION STAGE</div>
              <div style={{position:"relative"}}>
                <div style={{position:"absolute",top:13,left:14,right:14,height:2,background:C.dim}}/>
                <div style={{display:"flex",justifyContent:"space-between",position:"relative"}}>
                  {PROSECUTION_STAGES.map((s,i)=>{
                    const past=i<=stageIdx;
                    return <div key={s.id} onClick={()=>setStage(s.id)} style={{display:"flex",flexDirection:"column",alignItems:"center",gap:4,cursor:"pointer",minWidth:52}}>
                      <div style={{width:26,height:26,borderRadius:"50%",background:past?s.color:C.dim,border:`2px solid ${past?s.color:C.border}`,display:"flex",alignItems:"center",justifyContent:"center",fontSize:9,color:past?"#000":C.muted,fontWeight:700,zIndex:1,transition:"all 0.3s"}}>{i+1}</div>
                      <div style={{fontSize:8,color:s.id===stage?s.color:C.muted,textAlign:"center",maxWidth:52,lineHeight:1.3,fontFamily:"monospace"}}>{s.label}</div>
                    </div>;
                  })}
                </div>
              </div>
            </div>
            <div style={{fontSize:10,color:C.muted,letterSpacing:"0.1em",marginBottom:8}}>KEY DEADLINES</div>
            {deadlines.map((d,i)=>{
              const dDate=new Date(d.date).getTime();
              const daysLeft=Math.round((dDate-today)/86400000);
              const urgent=daysLeft<60&&daysLeft>=0;
              const passed=daysLeft<0;
              return <div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 14px",marginBottom:5,background:C.panel,border:`1px solid ${passed?C.muted+"20":urgent?C.red+"35":C.border}`,borderRadius:7}}>
                <div><div style={{fontSize:12,color:passed?C.muted:C.text,fontWeight:600}}>{d.label}</div><div style={{fontSize:10,color:C.muted}}>{d.note}</div></div>
                <div style={{textAlign:"right"}}><div style={{fontSize:12,fontFamily:"monospace",color:passed?C.muted:urgent?C.red:C.green}}>{d.date}</div><div style={{fontSize:10,color:passed?C.muted:urgent?C.red:C.muted}}>{passed?`${Math.abs(daysLeft)}d ago`:daysLeft===0?"TODAY":`${daysLeft}d left`}</div></div>
              </div>;
            })}
          </>
        )}
      </div>
    </div>
  );
}

// ══════════════════════════════════════════════════════════════════════════════
//  MAIN APP
// ══════════════════════════════════════════════════════════════════════════════
export default function PatentGuard(){
  const [tab,setTab]=useState("editor");
  const [inputText,setInputText]=useState("");
  const [patentDB,setPatentDB]=useState([]);
  const [dbCount,setDbCount]=useState(0);
  const [results,setResults]=useState([]);
  const [analysis,setAnalysis]=useState(null);
  const [scanning,setScanning]=useState(false);
  const [analyzing,setAnalyzing]=useState(false);
  const [scanMs,setScanMs]=useState(null);
  const [domainQ,setDomainQ]=useState("");
  const [domainLoad,setDomainLoad]=useState(false);
  const [ledger,setLedger]=useState([]);
  const [vault,setVault]=useState([]);
  const [pendingVault,setPendingVault]=useState([]);
  const [pending,setPending]=useState([]);
  const [editorData,   setEditorData]   = useState(null);  // template export
  const [appView,      setAppView]      = useState('template'); // 'template'|'editor'
  const [releasedCount,setReleasedCount]=useState(0);
  const [jurisdiction,setJurisdiction]=useState("US");
  const [backendOk,setBackendOk]=useState(null);
  const debounceRef=useRef(null);

  useEffect(()=>{
    fetch(`${API_BASE}/health`,{headers:FORM_HEADERS}).then(r=>setBackendOk(r.ok)).catch(()=>setBackendOk(false));
    ledgerGetAll().then(entries=>{
      setLedger(entries);
      const merged=entries.map(e=>({id:e.id,title:e.title,abstract:e.abstract||"",year:new Date(e.timestamp).getFullYear(),assignee:"Institution Upload",source:"ledger",tokenData:e.tokenData,url:null}));
      setPatentDB(merged); setDbCount(merged.length);
    });
    vaultGetAll().then(setVault);
    pendingVaultGetAll().then(setPendingVault);
    pendingGetAll().then(setPending);
    checkAndReleaseDuePatents(released=>{
      if(released.length>0){
        setReleasedCount(released.length);
        pendingVaultGetAll().then(setPendingVault);
        ledgerGetAll().then(es=>setLedger(es));
      }
    });
  },[]);

  const onUploadSuccess=(entry)=>{
    setLedger(prev=>[entry,...prev]);
    setVault(prev=>[entry,...prev]);
    setPatentDB(prev=>{const u=[...prev,{id:entry.id,title:entry.title,abstract:entry.abstract||"",year:new Date(entry.timestamp).getFullYear(),assignee:"Institutional",source:"ledger",tokenData:entry.tokenData,url:null}];setDbCount(u.length);return u;});
    setTab("ledger");
  };

  async function loadDomain(q){
    if(!q.trim())return; setDomainLoad(true);
    try{
      const patents=await searchUSPTO(q,40);
      setPatentDB(prev=>{const ids=new Set(prev.map(p=>p.id));const merged=[...prev,...patents.filter(p=>!ids.has(p.id))];setDbCount(merged.length);return merged;});
    }catch{}finally{setDomainLoad(false);}
  }

  useEffect(()=>{
    if(debounceRef.current) clearTimeout(debounceRef.current);
    if(inputText.trim().length<20){setResults([]);setAnalysis(null);return;}
    setScanning(true);
    debounceRef.current=setTimeout(async()=>{
      const t0=performance.now();
      const scored=patentDB.map(p=>({...p,score:semanticScore(inputText,p)})).filter(p=>p.score>0.06).sort((a,b)=>b.score-a.score).slice(0,8);
      setScanMs((performance.now()-t0).toFixed(1)); setResults(scored); setScanning(false);
      if(scored.length>0){
        setAnalyzing(true); setAnalysis(null);
        try{setAnalysis(await analyzePatent(inputText,scored,jurisdiction));}catch{}
        finally{setAnalyzing(false);}
      }
    },900);
    return()=>clearTimeout(debounceRef.current);
  },[inputText,patentDB,jurisdiction]);

  const topScore=results[0]?.score||0;
  const riskLevel=topScore>0.65?"HIGH RISK":topScore>0.35?"CAUTION":topScore>0?"SAFE":null;

  // Reset editor view when switching away from template tab
  const handleTabChange = (newTab) => {
    if (newTab !== "template") setAppView("template");
    setTab(newTab);
  };
  const TABS=[
    {key:"editor",  icon:"📄",label:"Editor"},
    {key:"upload",  icon:"⬆", label:"Upload"},
    {key:"ledger",  icon:"⛓", label:"Ledger",badge:ledger.length},
    {key:"pending", icon:"⏳", label:"Pending",badge:pendingVault.length},
    {key:"vault",   icon:"🗄", label:"Vault"},
    {key:"laws",    icon:"⚖", label:"Laws"},
    {key:"template",icon:"📋",label:"Template",badge:editorData?1:0},
    {key:"tracker", icon:"📅",label:"Tracker"},
    {key:"chat",    icon:"🤖",label:"AI Chat"},
  ];

  return (
    <div style={{height:"100vh",display:"flex",flexDirection:"column",background:C.bg,fontFamily:"'Courier New',monospace",color:C.text,overflow:"hidden"}}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=Syne:wght@400;600;700;800&display=swap');
        *{box-sizing:border-box;margin:0;padding:0}
        ::-webkit-scrollbar{width:4px}::-webkit-scrollbar-track{background:${C.bg}}::-webkit-scrollbar-thumb{background:${C.dim};border-radius:2px}
        textarea,input{outline:none}
        @keyframes spin{to{transform:rotate(360deg)}}
        @keyframes pulse{0%,100%{opacity:1}50%{opacity:0.3}}
        @keyframes slideUp{from{opacity:0;transform:translateY(6px)}to{opacity:1;transform:translateY(0)}}
        @keyframes shimmer{0%{transform:translateX(-100%)}100%{transform:translateX(100%)}}
        .card-in{animation:slideUp 0.3s ease forwards}
      `}</style>

      {/* HEADER */}
      <div style={{borderBottom:`1px solid ${C.border}`,padding:"10px 20px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"#08081a",flexShrink:0}}>
        <div style={{display:"flex",alignItems:"center",gap:12}}>
          <div style={{width:32,height:32,background:`linear-gradient(135deg,${C.accent},${C.cyan})`,borderRadius:8,display:"flex",alignItems:"center",justifyContent:"center",fontSize:16}}>⚖</div>
          <div>
            <span style={{fontFamily:"'Syne',sans-serif",fontWeight:800,fontSize:16,letterSpacing:"0.04em"}}>PATENT<span style={{color:C.accent}}>GUARD</span></span>
            <span style={{fontSize:9,color:C.muted,letterSpacing:"0.14em",marginLeft:10}}>v4 · GLOBAL LEDGER EDITION</span>
          </div>
        </div>
        <div style={{display:"flex",gap:10,alignItems:"center"}}>
          <span style={{fontSize:10,color:backendOk===null?C.amber:backendOk?C.green:C.red,display:"flex",alignItems:"center",gap:5}}>
            <span style={{width:6,height:6,borderRadius:"50%",background:backendOk===null?C.amber:backendOk?C.green:C.red,display:"inline-block",animation:"pulse 2s infinite"}}/>
            {backendOk===null?"CONNECTING":backendOk?"BACKEND ONLINE":"BACKEND OFFLINE"}
          </span>
          <Pill color={C.gold}>⛓ {ledger.length} PATENTS</Pill>
          <Pill color={C.accent}>DB: {dbCount}</Pill>
        </div>
      </div>

      {/* DOMAIN BAR */}
      <div style={{borderBottom:`1px solid ${C.border}`,padding:"6px 20px",display:"flex",gap:8,alignItems:"center",background:C.bg,flexShrink:0}}>
        <span style={{fontSize:9,color:C.muted,letterSpacing:"0.1em",whiteSpace:"nowrap"}}>USPTO LIVE:</span>
        <PGInput value={domainQ} onChange={e=>setDomainQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&loadDomain(domainQ)} placeholder={`"machine learning" · "drug delivery" · "autonomous vehicle"`} style={{flex:1}}/>
        <Btn onClick={()=>loadDomain(domainQ)} disabled={domainLoad||!domainQ.trim()}>{domainLoad?<><Spinner/> LOADING</>:"FETCH →"}</Btn>
      </div>

      {/* MAIN */}
      <div style={{flex:1,display:"flex",overflow:"hidden"}}>

        {/* LEFT */}
        <div style={{flex:1,display:"flex",flexDirection:"column",borderRight:`1px solid ${C.border}`,overflow:"hidden"}}>
          <div style={{display:"flex",borderBottom:`1px solid ${C.border}`,padding:"0 14px",gap:0,paddingTop:6,background:C.bg,flexShrink:0,overflowX:"auto"}}>
            {TABS.map(t=>(
              <button key={t.key} onClick={()=>handleTabChange(t.key)} style={{padding:"8px 13px",border:"none",background:"transparent",fontFamily:"monospace",fontSize:10,fontWeight:700,letterSpacing:"0.08em",textTransform:"uppercase",cursor:"pointer",whiteSpace:"nowrap",color:tab===t.key?C.accent:C.muted,borderBottom:tab===t.key?`2px solid ${C.accent}`:"2px solid transparent",transition:"all 0.2s"}}>
                {t.icon} {t.label}
                {t.badge>0&&<span style={{marginLeft:4,background:`${C.cyan}25`,color:C.cyan,fontSize:8,padding:"1px 4px",borderRadius:6}}>{t.badge}</span>}
              </button>
            ))}
          </div>

          <div style={{flex:1,overflow:"hidden",display:"flex",flexDirection:"column"}}>
            {tab==="editor"&&(
              <>
                <div style={{padding:"6px 16px",borderBottom:`1px solid ${C.border}`,display:"flex",gap:12,alignItems:"center",flexShrink:0}}>
                  <span style={{fontSize:10,color:C.muted}}>WORDS <span style={{color:C.accent}}>{inputText.trim()?inputText.trim().split(/\s+/).length:0}</span></span>
                  <div style={{display:"flex",gap:3,alignItems:"center"}}>
                    <span style={{fontSize:9,color:C.muted}}>JUR:</span>
                    {Object.values(JURISDICTIONS).map(j=><Btn key={j.code} onClick={()=>setJurisdiction(j.code)} small color={jurisdiction===j.code?C.accent:C.muted} style={{padding:"2px 6px",fontSize:9}}>{j.flag}{j.code}</Btn>)}
                  </div>
                  {scanning&&<span style={{fontSize:10,color:C.amber,animation:"pulse 1s infinite"}}>● SCANNING {dbCount}...</span>}
                  {!scanning&&scanMs&&results.length>0&&<span style={{fontSize:10,color:C.green}}>✓ {scanMs}ms</span>}
                  {riskLevel&&!scanning&&<div style={{marginLeft:"auto"}}><Badge color={riskLevel==="HIGH RISK"?C.red:riskLevel==="CAUTION"?C.amber:C.green} icon={riskLevel==="HIGH RISK"?"✗":riskLevel==="CAUTION"?"⚠":"✓"} label={riskLevel}/></div>}
                </div>
                <div style={{flex:1,position:"relative",overflow:"hidden"}}>
                  {scanning&&<div style={{position:"absolute",top:0,left:0,right:0,height:2,background:`${C.accent}25`,zIndex:10,overflow:"hidden"}}><div style={{height:"100%",width:"40%",background:`linear-gradient(90deg,transparent,${C.accent},transparent)`,animation:"shimmer 1s ease infinite"}}/></div>}
                  <textarea value={inputText} onChange={e=>setInputText(e.target.value)}
                    placeholder={`Describe your invention here...\n\nPatentGuard will:\n• Scan USPTO patents + global ledger in real time\n• Check ${JURISDICTIONS[jurisdiction]?.name} law (§101/§102/§103/§112)\n• Provide AI-powered conflict analysis\n• Reference verified institutional patents\n\nExample: "A wearable exoskeleton device that uses pneumatic actuators to assist human arm movement, providing assistive force proportional to detected muscle tension via electromyographic sensors..."`}
                    style={{width:"100%",height:"100%",padding:"22px",background:"#08081a",color:C.text,fontFamily:"'Space Mono',monospace",fontSize:13,lineHeight:1.85,border:"none",resize:"none"}}
                  />
                </div>
              </>
            )}
            {tab==="upload"   &&<UploadPanel/>}
            {tab==="ledger"   &&<LedgerPanel entries={ledger}/>}
            {tab==="laws"     &&<LawsPanel jurisdiction={jurisdiction} setJurisdiction={setJurisdiction}/>}
            {tab==="template"&&(
              appView==="editor"&&editorData?(
                <ApplicationEditorView C={C} data={editorData}
                  onSendToGov={async()=>{
                    const {vals,figures}=editorData;
                    const rawText=[vals.title,vals.field,vals.background,vals.summary,vals.description,vals.abstract].filter(Boolean).join("\n\n");
                    const salt=Array.from(crypto.getRandomValues(new Uint8Array(16))).join("");
                    const zk=await zkCommit(rawText,salt);
                    const userKey=await generateUserKey(rawText,Date.now());
                    const ipfsCid=await generateIPFSCid(rawText);
                    const td=tokenize(rawText);
                    const ts=Date.now();
                    const entryId=`PG-${ts.toString(36).toUpperCase()}`;
                    const sched=PUB_SCHEDULES.find(s=>s.id==="standard");
                    const sub={
                      id:entryId,title:vals.title||"Untitled Patent",userKey,
                      contentHash:zk.contentHash,ipfsCid,
                      zkCommitment:zk.commitment,zkNullifier:zk.nullifier,
                      zkBindingKey:zk.bindingKey,zkSalt:zk.salt,proofType:zk.proofType,
                      publicationSchedule:sched.id,publicationMonths:sched.months,
                      timestamp:ts,submittedAt:new Date().toISOString(),
                      status:"SUBMITTED",source:"user_portal",tokenData:td,
                      abstract:vals.abstract||"",templateData:vals,figures,
                      institution:"PatentGuard User Submission",
                    };
                    const ok=await submitToGovQueue(sub);
                    await vaultSave(sub);
                    alert(ok?`✓ Submitted to Government Portal\nApplication ID: ${entryId}`:"✗ Failed to submit");
                  }}
                />
              ):(
                <TemplatePanel C={C} onExportToEditor={(data)=>{setEditorData(data);setAppView("editor");}}/>
              )
            )}
            {tab==="tracker"  &&<TrackerPanel ledger={ledger}/>}
            {tab==="chat"     &&<ChatBot ledger={ledger} jurisdiction={jurisdiction} setJurisdiction={setJurisdiction}/>}
            {tab==="pending"&&(
              <div style={{flex:1,overflowY:"auto",padding:20}}>
                <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:4}}>
                  <div>
                    <div style={{fontFamily:"monospace",fontSize:15,fontWeight:700,marginBottom:2}}>⏳ Pending Publication Vault</div>
                    <div style={{fontSize:10,color:C.muted}}>Patents awaiting their locked publication date — not yet visible in global ledger</div>
                  </div>
                  <Pill color={C.amber}>{pendingVault.length} PENDING</Pill>
                </div>
                {releasedCount>0&&(
                  <div style={{padding:"10px 14px",background:`${C.green}12`,border:`1px solid ${C.green}40`,borderRadius:8,marginBottom:12,fontSize:11,color:C.green}}>
                    🎉 {releasedCount} patent{releasedCount>1?"s were":" was"} automatically released to the global ledger today.
                  </div>
                )}
                {pendingVault.length===0?(
                  <div style={{textAlign:"center",padding:"40px",color:C.muted}}>
                    <div style={{fontSize:36,marginBottom:12}}>⏳</div>
                    <div style={{fontSize:11,lineHeight:1.8}}>No patents pending publication.<br/>Patents with scheduled release dates appear here.</div>
                  </div>
                ):pendingVault.map(e=>{
                  const now=Date.now();
                  const daysLeft=Math.round((e.publicationDate-now)/86400000);
                  const overdue=daysLeft<0;
                  const urgent=daysLeft>=0&&daysLeft<30;
                  return (
                    <div key={e.id} style={{marginBottom:10,padding:"14px",background:C.panel,border:`1px solid ${overdue?C.green+"60":urgent?C.amber+"40":C.border}`,borderRadius:10}}>
                      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}>
                        <div>
                          <span style={{fontSize:10,color:C.accent,fontFamily:"monospace",fontWeight:700}}>{e.id}</span>
                          <span style={{fontSize:9,color:C.muted,marginLeft:8}}>Filed: {new Date(e.timestamp).toLocaleDateString()}</span>
                        </div>
                        <Pill color={overdue?C.green:urgent?C.amber:C.cyan} small>
                          {overdue?"🚀 RELEASING NOW":urgent?`⚠ ${daysLeft}d left`:`${daysLeft}d until pub`}
                        </Pill>
                      </div>
                      <div style={{fontSize:12,fontWeight:600,color:C.text,marginBottom:8}}>{e.title?.slice(0,80)}</div>
                      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:6,marginBottom:8}}>
                        <div style={{padding:"6px 8px",background:C.dim,borderRadius:6}}>
                          <div style={{fontSize:9,color:C.muted,marginBottom:2}}>SCHEDULE</div>
                          <div style={{fontSize:11,color:C.gold,fontFamily:"monospace"}}>{e.publicationSchedule?.toUpperCase()}</div>
                        </div>
                        <div style={{padding:"6px 8px",background:C.dim,borderRadius:6}}>
                          <div style={{fontSize:9,color:C.muted,marginBottom:2}}>PUBLICATION DATE</div>
                          <div style={{fontSize:11,color:C.amber,fontFamily:"monospace"}}>{e.pubDateStr?.slice(0,10)}</div>
                        </div>
                        <div style={{padding:"6px 8px",background:C.dim,borderRadius:6}}>
                          <div style={{fontSize:9,color:C.muted,marginBottom:2}}>LOCK HASH</div>
                          <div style={{fontSize:10,color:C.dim,fontFamily:"monospace"}}>{e.pubCommitment?.slice(0,12)}...</div>
                        </div>
                      </div>
                      <div style={{display:"flex",gap:6,alignItems:"center"}}>
                        <Pill color={C.gold} small>🔒 IMMUTABLE</Pill>
                        <Pill color={C.accent} small>ZK ✓</Pill>
                        {e.govKey&&<Pill color={C.green} small>DUAL-KEY ✓</Pill>}
                        <div style={{fontSize:10,color:C.muted,marginLeft:"auto"}}>Cannot change publication date after submission</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
            {tab==="vault"&&(
              <div style={{flex:1,overflowY:"auto",padding:20}}>
                <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:14}}>
                  <div><div style={{fontFamily:"monospace",fontSize:15,fontWeight:700,marginBottom:2}}>Personal Vault</div><div style={{fontSize:10,color:C.muted}}>Your documents — stored in your PatentGuard account · ledger-bound items are locked</div></div>
                  <Pill color={C.green}>{vault.length} DOCS</Pill>
                </div>
                {vault.length===0?(
                  <div style={{textAlign:"center",padding:"40px",color:C.muted}}><div style={{fontSize:36,marginBottom:12}}>🗄</div><div style={{fontSize:11,lineHeight:1.8}}>No documents yet.<br/>Upload via the Upload tab.</div></div>
                ):vault.map(doc=>{
                  const onLedger = ledger.some(e=>e.id===doc.id);
                  const pend     = pending.find(p=>p.id===doc.id);
                  const granted  = onLedger || ["GRANTED","CODE_ISSUED"].includes(pend?.status);
                  const inQueue  = pend && !granted && pend.status!=="REJECTED" && doc.status!=="WITHDRAWN";
                  return (
                  <div key={doc.id} style={{marginBottom:8,padding:"12px 14px",background:C.panel,border:`1px solid ${C.border}`,borderRadius:10}}>
                    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:5}}>
                      <span style={{fontSize:10,color:C.cyan,fontFamily:"monospace",fontWeight:700}}>{doc.id}</span>
                      {onLedger ? (
                        <span title="Published to the global ledger — immutable" style={{fontSize:9,color:C.gold,fontFamily:"monospace",fontWeight:700,letterSpacing:"0.06em"}}>🔒 ON LEDGER</span>
                      ) : inQueue ? (
                        <button title="Withdraw this submission from the government queue" onClick={async()=>{ if(!window.confirm("Withdraw this submission from the government queue? You can re-submit later.")) return; await withdrawSubmission(doc.id); setPending(prev=>prev.filter(p=>p.id!==doc.id)); setVault(prev=>prev.map(d=>d.id===doc.id?{...d,status:"WITHDRAWN"}:d)); }} style={{background:"transparent",border:`1px solid ${C.amber}50`,color:C.amber,cursor:"pointer",fontSize:9,fontFamily:"monospace",fontWeight:700,borderRadius:5,padding:"2px 7px"}}>↩ WITHDRAW</button>
                      ) : (
                        <button title="Delete this draft" onClick={async()=>{await vaultDelete(doc.id);setVault(prev=>prev.filter(d=>d.id!==doc.id));}} style={{background:"transparent",border:"none",color:C.muted,cursor:"pointer",fontSize:13}}>✕</button>
                      )}
                    </div>
                    <div style={{fontSize:12,fontWeight:600,color:C.text,marginBottom:6}}>{doc.title?.slice(0,70)}</div>
                    <div style={{display:"flex",gap:5,flexWrap:"wrap"}}>
                      {onLedger&&<Pill color={C.gold} small>🔒 GRANTED · LEDGER</Pill>}
                      {inQueue&&<Pill color={C.amber} small>⏳ IN GOV QUEUE{pend?.status?` · ${pend.status}`:""}</Pill>}
                      {doc.status==="WITHDRAWN"&&<Pill color={C.muted} small>↩ WITHDRAWN</Pill>}
                      {doc.govCode&&<Pill color={C.gold} small>🏛 {doc.govCode}</Pill>}
                      {doc.ipfsCid&&<Pill color={C.cyan} small>IPFS ✓</Pill>}
                      {doc.tokenData?.stats&&<Pill color={C.accent} small>{doc.tokenData.stats.tokens} tokens</Pill>}
                    </div>
                    <div style={{fontSize:9,color:C.muted,marginTop:5,fontFamily:"monospace"}}>{new Date(doc.uploadedAt||doc.timestamp).toLocaleDateString()}</div>
                  </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* RIGHT: Results */}
        <div style={{width:370,display:"flex",flexDirection:"column",background:"#07070f",overflow:"hidden"}}>
          <div style={{padding:"10px 14px",borderBottom:`1px solid ${C.border}`,display:"flex",justifyContent:"space-between",alignItems:"center",flexShrink:0}}>
            <span style={{fontSize:10,color:C.muted,letterSpacing:"0.13em",fontWeight:700}}>SIMILARITY RESULTS</span>
            {results.length>0&&<Pill color={C.accent} small>{results.length} MATCHES</Pill>}
          </div>
          <div style={{flex:1,overflowY:"auto",padding:10}}>
            {results.length===0&&!scanning&&(
              <div style={{textAlign:"center",padding:"50px 20px",color:C.dim}}>
                <div style={{fontSize:36,marginBottom:12}}>⚖</div>
                <div style={{fontSize:10,lineHeight:2,letterSpacing:"0.09em",color:C.muted}}>{dbCount>0?"START TYPING TO SCAN":"FETCH USPTO PATENTS\nOR UPLOAD TO LEDGER"}</div>
              </div>
            )}
            {(analyzing||analysis)&&results.length>0&&(
              <div style={{marginBottom:10,padding:"12px 14px",background:`${C.accent}0a`,border:`1px solid ${C.accent}30`,borderRadius:10,animation:"slideUp 0.3s ease"}}>
                <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}>
                  <span style={{fontSize:10,color:C.accent,letterSpacing:"0.12em",fontWeight:700}}>⚡ AI ANALYSIS · {JURISDICTIONS[jurisdiction]?.flag} {jurisdiction}</span>
                  {analyzing&&<Spinner/>}
                </div>
                {analysis&&(
                  <>
                    <p style={{fontSize:11.5,lineHeight:1.75,color:"#9090c0",marginBottom:10}}>{analysis.assessment}</p>
                    {analysis.legalIssues?.length>0&&<div style={{marginBottom:8}}><div style={{fontSize:9,color:C.muted,letterSpacing:"0.1em",marginBottom:4}}>LEGAL ISSUES</div>{analysis.legalIssues.map((l,i)=><div key={i} style={{fontSize:11,color:`${C.red}cc`,padding:"2px 0 2px 10px",borderLeft:`2px solid ${C.red}30`,marginBottom:2}}>{l}</div>)}</div>}
                    {analysis.overlaps?.length>0&&<div style={{marginBottom:8}}><div style={{fontSize:9,color:C.muted,letterSpacing:"0.1em",marginBottom:4}}>OVERLAPPING CLAIMS</div>{analysis.overlaps.map((o,i)=><div key={i} style={{fontSize:11,color:"#5050a0",padding:"2px 0 2px 10px",borderLeft:`2px solid ${C.accent}30`,marginBottom:2}}>{o}</div>)}</div>}
                    {analysis.suggestions?.length>0&&<div style={{marginBottom:8}}><div style={{fontSize:9,color:C.muted,letterSpacing:"0.1em",marginBottom:4}}>DIFFERENTIATION IDEAS</div>{analysis.suggestions.map((s,i)=><div key={i} style={{fontSize:11,color:`${C.green}90`,padding:"2px 0 2px 10px",borderLeft:`2px solid ${C.green}30`,marginBottom:2}}>{s}</div>)}</div>}
                    <div style={{display:"flex",alignItems:"center",gap:8,paddingTop:8,borderTop:`1px solid ${C.border}`}}>
                      <Badge color={analysis.verdict==="HIGH RISK"?C.red:analysis.verdict==="CAUTION"?C.amber:C.green} icon={analysis.verdict==="HIGH RISK"?"✗":"⚠"} label={analysis.verdict}/>
                      <span style={{fontSize:10,color:C.muted}}>{analysis.verdictReason}</span>
                    </div>
                  </>
                )}
              </div>
            )}
            {results.map((p,i)=>{
              const pct=Math.round(p.score*100);
              const isLedger=p.source==="ledger";
              return <div key={p.id} className="card-in" style={{marginBottom:8,padding:"12px 14px",background:isLedger?`${C.gold}08`:i===0&&pct>40?"#150808":C.panel,border:`1px solid ${isLedger?C.gold+"30":pct>65?C.red+"25":pct>35?C.amber+"25":C.border}`,borderRadius:10,animationDelay:`${i*0.04}s`,opacity:0}}>
                <div style={{display:"flex",justifyContent:"space-between",marginBottom:4,gap:8}}>
                  <div style={{display:"flex",gap:5,alignItems:"center",flexWrap:"wrap"}}>
                    {p.url?<a href={p.url} target="_blank" rel="noopener noreferrer" style={{fontSize:10,color:C.accent,fontWeight:700,textDecoration:"none"}}>{p.id} ↗</a>:<span style={{fontSize:10,color:isLedger?C.gold:C.amber,fontWeight:700}}>{p.id.slice(0,22)}</span>}
                    {isLedger&&<Pill color={C.gold} small>⛓ LEDGER</Pill>}
                  </div>
                  <span style={{fontSize:10,color:C.muted}}>{p.year}</span>
                </div>
                <div style={{fontSize:12,fontFamily:"'Syne',sans-serif",fontWeight:600,color:C.text,marginBottom:6,lineHeight:1.4}}>{p.title?.slice(0,80)}{p.title?.length>80?"...":""}</div>
                <ScoreBar score={p.score}/>
                <div style={{display:"flex",justifyContent:"space-between",marginTop:7,alignItems:"center"}}>
                  <span style={{fontSize:10,color:C.muted,maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{p.assignee}</span>
                  <span style={{fontSize:10,fontWeight:700,color:pct>65?C.red:pct>35?C.amber:C.green}}>{pct}% MATCH</span>
                </div>
              </div>;
            })}
            {results.length>0&&<div style={{padding:"10px 12px",background:C.dim,border:`1px solid ${C.border}`,borderRadius:8,marginTop:4}}>
              <div style={{fontSize:9,color:C.muted,letterSpacing:"0.12em",marginBottom:6}}>SCAN STATS</div>
              {[["DB size",dbCount.toLocaleString()],["Ledger",ledger.length+" verified"],["Scan",scanMs?`${scanMs}ms`:"—"],["Jurisdiction",JURISDICTIONS[jurisdiction]?.flag+" "+jurisdiction],["Backend",backendOk?"Python + spaCy":"Browser"],["Complexity","O(n·k) → O(log n)"]].map(([k,v])=>(
                <div key={k} style={{display:"flex",justifyContent:"space-between",padding:"2px 0"}}>
                  <span style={{fontSize:10,color:C.muted}}>{k}</span>
                  <span style={{fontSize:10,color:"#3a3a6a",fontFamily:"monospace"}}>{v}</span>
                </div>
              ))}
            </div>}
          </div>
        </div>
      </div>
    </div>
  );
}
